# Generated by Django 3.0.7 on 2020-06-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=30)),
                ('cpf', models.IntegerField()),
                ('data_nascimento', models.DateField()),
                ('rua', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
                ('cep', models.IntegerField()),
                ('bairro', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('numero_telefome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.CharField(max_length=30)),
                ('colaborador', models.CharField(max_length=30)),
                ('cliente', models.CharField(max_length=30)),
                ('titulo', models.CharField(max_length=30)),
                ('material', models.CharField(max_length=30)),
                ('quantidade', models.IntegerField()),
                ('valor', models.FloatField()),
                ('arquivo', models.FileField(upload_to='projeto/anexo')),
            ],
        ),
    ]
