# Generated by Django 3.0.7 on 2020-06-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_projeto_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='responsavel',
            field=models.CharField(default='1', max_length=30),
            preserve_default=False,
        ),
    ]
