# Generated by Django 3.0.7 on 2020-06-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20200629_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
